Bump hackney to fix TLS related issues
mozilla/reticulum pull request #425
Opened 2020-10-22 17:25 UTC by keianhzo

In some platforms like Mac Catalina there seems to be some incompatibility between the hackney version  that we were using and the OS. That caused an error when accessing the admin at https://hubs.local:4000/?skipadmin:
```Missing file index.html. Please try again.```

Bumping the hackney version to 1.16.0 seems to fix that issues for Mac and WSL.

2020-11-10 14:38 UTC, keianhzo commented
@brianpeiris can you take a look and see if everything looks good in your setup?

2020-11-11 13:49 UTC, brianpeiris requested changes
Confirmed this works on my setup, but you'll need to include the modifications to the mix.lock file before merging this.

2021-01-05 23:44 UTC, robinkwilson commented
Bump this also fixed my missing `index.html` issue. I'd like to get this merged.

2021-01-06 09:16 UTC, keianhzo commented
Closing as it's being merged with https://github.com/mozilla/reticulum/pull/447

2021-01-06 09:16 UTC, closed without merging