Portal/internal endpoints /v1/internal -> /api-internal/v1
mozilla/reticulum pull request #580
Opened 2022-04-22 01:21 UTC by robinkwilson

To ensure the internal endpoints are private and secure, organize the endpoint under another directory.

2022-04-22 01:53 UTC, netpro2k requested changes
We probably don't want the second copy of the route under `/api` and we should see what `as: :api_v1` does and consider changing it. Otherwise lgtm.

2022-04-22 01:53 UTC, netpro2k commented on lib/ret_web/router.ex
> +    scope "/api-internal/v1", as: :api_v1 do
Is there a reason we want these routes on both `/api/api-internal/v1` and `/api-internal/v1`?

2022-04-22 01:53 UTC, netpro2k commented on lib/ret_web/router.ex
> +      get("/presence", ApiInternal.PresenceController, :show)
Looks like you are missing V1 here?
```suggestion
      get("/presence", ApiInternal.V1.PresenceController, :show)
```

2022-04-22 01:53 UTC, netpro2k commented on lib/ret_web/router.ex
> +    scope "/v1", as: :api_v1 do
I forget what `as: :api_v1` does here but we depending on what it does we maybe want something like `as: api_internal_v1`. My guess is its for generating utility functions.

2022-05-05 18:57 UTC, brianpeiris approved these changes
LGTM

2022-05-05 19:11 UTC, merged